### ISSUE TITLE
Adding conda package

### ISSUE THREAD

**Issue by jakirkham** [Exteris/h5pickle#1]
Would be great to have this available as a [conda]( https://conda.io/docs/ ) package. Ideally this could be included in [conda-forge]( https://conda-forge.org/ ).

**Comment by DaanVanVugt** [comment]
I agree, I'm looking into it. See https://github.com/conda-forge/staged-recipes/pull/4450

**Comment by DaanVanVugt** [comment]
Merged to conda-forge/staged-recipes as h5pickle
