### ISSUE TITLE
Unable to create file when opened with mode='w'

### ISSUE THREAD

**Issue by aasensio** [Exteris/h5pickle#3]
When trying to create a file by truncating any existing file using

    f = h5pickle.File('test.h5','w')

gives

    Unable to create file (unable to truncate a file which is already open)

even if the file does not exists. Is this because, as you say in the README file, "Note that not all features of h5py are supported yet. Pull requests are very welcome."?

**Comment by DaanVanVugt** [comment]
Yes, exactly. Every process tries to open the file now, with the 'w' flag, which fails for every process but the first. For writing from multiple process to HDF5 files the MPI IO api is necessary, which we do not provide anything for (yet).

**Comment by aasensio** [comment]
But this happens even in a single process case. I open a Python console, import h5pickle and try to open a file in 'w' mode and it fails. No multiprocessing involved. Am I missing something? I need your solution because I need to broadcast a large class with mpi4py that imports h5py, but only one process is opening the file.

**Comment by DaanVanVugt** [comment]
Ah, it is an issue in the implementation where the file is opened twice, which does not matter for read-only. I will push a fix.

Note that I would recommend against pickling and sending files with mode 'w' since this is almost guaranteed to not work. I think you want something like http://docs.h5py.org/en/latest/swmr.html

**Comment by DaanVanVugt** [comment]
This problem is fixed in 0.3 now on PyPI (and a git tag in this repository).
How it would work with SWMR I have not thought about much more, please let me know if you get that working :)
